#SSL properties, check notes for disabling
server:
  port: 8443
  ssl:
    key-store: classpath:keystore/powerofattorney.p12
    key-store-type: PKCS12
    key-store-password: powerofattorney
    key-alias: powerofattorney
    enabled: true

#Different properties since they are their own microservice
adapter:
    poa:
      baseUrl: "http://localhost:8080"
      connectionTimeout: 2000
    account:
      baseUrl: "http://localhost:8080"
      connectionTimeout: 2000
    creditcard:
      baseUrl: "http://localhost:8080"
      connectionTimeout: 2000
    debitcard:
      baseUrl: "http://localhost:8080"
      connectionTimeout: 2000

#If enabled, users only can reach to resources that concerns themselves
application:
  security:
    enabled: true